### ISSUE TITLE
Update prometheus config to include the new metrics endpoint

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-demo#37]
Relates to: https://github.com/torrust/torrust-demo/issues/36

```yaml
global:
  scrape_interval: 15s # How often to scrape metrics

scrape_configs:
  - job_name: "tracker_stats"
    metrics_path: "/api/v1/stats"
    params:
      token: ["MyAccessToken"]
      format: ["prometheus"]
    static_configs:
      - targets: ["tracker:1212"]

  - job_name: "tracker_metrics"
    metrics_path: "/api/v1/metrics"
    params:
      token: ["MyAccessToken"]
      format: ["prometheus"]
    static_configs:
      - targets: ["tracker:1212"]
```

NOTICE: No metrics with the same names exist, so we do not need to relabel configs (`relabel_configs` section).
