### ISSUE TITLE
Docker Security Overhaul: Limit System Calls Using Seccomp

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-demo#42]
Use [Seccomp security profiles](https://docs.docker.com/engine/security/seccomp/) to restrict the actions available within the container

https://docs.docker.com/engine/security/seccomp/

Example:

```yaml
# seccomp.yaml
{
  "defaultAction": "SCMP_ACT_ALLOW",
  "syscalls": [
    {
      "names": ["ptrace"],
      "action": "SCMP_ACT_KILL"
    }
  ]
}
```
