### ISSUE TITLE
Update Tracker and Index configuration

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-demo#8]
Relates to:
 - https://github.com/torrust/torrust-tracker/issues/401
 - https://github.com/torrust/torrust-index/issues/591

More changes related to the configuration have been merged in the Tracker and Index repos.

We have to update the Tracker and Index configuration files in the demo.

### Old config files

Tracker (`storage/tracker/etc/tracker.toml`)

```toml
[logging]
log_level = "info"

[core]
mode = "public"

[core.tracker_policy]
persistent_torrent_completed_stat = true

[core.announce_policy]
interval = 300
interval_min = 300

[core.net]
on_reverse_proxy = true

[core.database]
driver = "Sqlite3"
path = "/var/lib/torrust/tracker/database/sqlite3.db"

[[udp_trackers]]
bind_address = "0.0.0.0:6969"

[[http_trackers]]
bind_address = "0.0.0.0:7070"

[http_api]
bind_address = "0.0.0.0:1212"
```

Index (`storage/index/etc/index.toml`)

```toml
[tracker]
api_url = "http://tracker:1212"
url = "udp://tracker.torrust-demo.com:6969"

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/sqlite3.db?mode=rwc"

[mail.smtp]
port = 1025
server = "mailcatcher"
```

### New config files

Tracker (`storage/tracker/etc/tracker.toml`)

```toml
version = "2"

[logging]
threshold = "info"

[core]
listed = false
private = false

[core.tracker_policy]
persistent_torrent_completed_stat = true

[core.announce_policy]
interval = 300
interval_min = 300

[core.net]
on_reverse_proxy = true

[core.database]
driver = "Sqlite3"
path = "/var/lib/torrust/tracker/database/sqlite3.db"

[[udp_trackers]]
bind_address = "0.0.0.0:6969"

[[http_trackers]]
bind_address = "0.0.0.0:7070"

[http_api]
bind_address = "0.0.0.0:1212"
```

Index (`storage/index/etc/index.toml`)

```toml
version = "2"

[tracker]
api_url = "http://tracker:1212"
listed = false
private = false
url = "udp://tracker.torrust-demo.com:6969"

[database]
connect_url = "sqlite:///var/lib/torrust/index/database/sqlite3.db?mode=rwc"

[mail.smtp]
port = 1025
server = "mailcatcher"
```
